# Generated by Django 4.2.4 on 2023-08-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authetication', '0002_remove_user_name_user_username_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
