# Generated by Django 4.2.4 on 2023-08-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authetication', '0006_remove_user_phone_number_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
